export const SET_TOKEN = 'SET_TOKEN';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const SET_ARTISTS = 'SET_ARTISTS';
export const SET_USER = "SET_USER";
export const SET_TRACKS_LONG_TERM = 'SET_TRACKS_LONG_TERM';
export const SET_TRACKS_SHORT_TERM = 'SET_TRACKS_SHORT_TERM';
export const SET_TRACKS_MEDIUM_TERM = 'SET_TRACKS_MEDIUM_TERM';
export const SET_TRACKS_FILTER = 'SET_TRACKS_FILTER0;'